apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: centos-home-nfs
  name: centos-home-nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15G
status: {}
