apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
spec:
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: should be fqdn service??
    server: nfs-service.nfs-test.svc.cluster.local
    path: "/nfs"
