apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nfs
  name: zfs-nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
      fsType: zfs
status: {}
