kind: Service
apiVersion: v1
metadata:
  labels:
    service: wlaw-nfs
  name: wlaw-nfs-service
spec:
  selector:
    service: wlaw-nfs
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
  - name: rpcbind
    port: 111
    targetPort: 111
